;	.: On Sale :.
Item = TT_RuleBook|NONE|JobMiscFaction
Item = TT_BoardMisc|NONE|JobMiscFaction
Item = TT_CardPack_L|NONE|JobMiscFaction|NONE|NONE|5|20
Item = TT_CardPack_L|NONE|JobMiscFaction|NONE|NONE|4|40
Item = TT_CardPack_L|NONE|JobMiscFaction|NONE|NONE|3|60
Item = TT_CardPack_L|NONE|JobMiscFaction|NONE|NONE|2|80
Item = TT_CardPack_L|NONE|JobMiscFaction
;
;	.: On Loot :.
Item = TT_NPCCardPack_L|NONE|-ActorTypeCreature,-ActorTypeDaedra,-ActorTypeDwarven,-ActorTypeGhost,-ManakinRace|NONE|-U/-S|1|20